<a href="https://colab.research.google.com/github/hhpark143/Week2_Pandas/blob/main/Session_2_Student_Worksheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📊 Session 2 — Student Worksheet (Pandas + Plotly)
Work in small groups. Find a CSV dataset on GitHub, load it in Colab, and adapt commands from the workbook.
Be ready to walk through your code at the end.

## Part 1 — Find a Dataset (GitHub)

In [3]:
csv_url = "https://raw.githubusercontent.com/MainakRepositor/Datasets/refs/heads/master/baby_names.csv"
csv_url

'https://raw.githubusercontent.com/MainakRepositor/Datasets/refs/heads/master/baby_names.csv'

## Part 2 — Load & Inspect

In [4]:
import pandas as pd

baby_names = pd.read_csv(csv_url)
baby_names.info()
#rows, cols = df.shape
#rows, cols

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 890627 entries, 0 to 890626
Data columns (total 6 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  890627 non-null  int64
 1   State       890627 non-null  object
 2   Sex         890627 non-null  object
 3   Year        890627 non-null  int64
 4   Name        890627 non-null  object
 5   Count       890627 non-null  int64
dtypes: int64(3), object(3)
memory usage: 40.8+ MB

## Part 3 — Explore & Clean

In [5]:
#aby_names.dtypes

#baby_names.isnull().sum().sort_values(ascending=False).head(10)

baby_names[baby_names.duplicated(keep=False)].head(10)

Empty DataFrame
Columns: [Unnamed: 0, State, Sex, Year, Name, Count]
Index: []

## Part 4 — Summarization

In [5]:
#category_col = 'REPLACE_ME'
#numeric_col = 'REPLACE_ME'

#by_cat = df.groupby(category_col)[numeric_col].sum().sort_values(ascending=False)
#by_cat.head(10)

bygender_name = baby_names.groupby('Sex')['Count'].sort_values(ascending=False)
bygender_name.head(10)

AttributeError: 'SeriesGroupBy' object has no attribute 'sumsort_values'

In [25]:
# Find the top 10 male baby names by count
male_babyname_counts = baby_names[baby_names['Sex'] == 'M'].groupby('Name')['Count'].sum().sort_values(ascending=False)
display(male_babyname_counts.head(10))

Name
James          989034
William        726093
John           615872
Robert         569342
Michael        456155
David          419782
Charles        413573
Christopher    290190
Thomas         288319
Joseph         265306
Name: Count, dtype: int64

In [6]:
female_babyname_counts = baby_names[baby_names['Sex'] == 'F'].groupby('Name')['Count'].sum().sort_values(ascending=False)
female_babyname_counts.head(10)

Name
Mary         648166
Elizabeth    226808
Betty        206953
Linda        200041
Barbara      181592
Patricia     178825
Sarah        173186
Margaret     168333
Dorothy      166371
Jennifer     163338
Name: Count, dtype: int64

In [9]:
#find the top 10 baby names by sex (M or F)

bygender_name = baby_names.groupby(['Sex','Name'])['Count'].sum().sort_values(ascending=False)
bygender_name.head(25)

Sex  Name
M    James          989034
     William        726093
F    Mary           648166
M    John           615872
     Robert         569342
     Michael        456155
     David          419782
     Charles        413573
     Christopher    290190
     Thomas         288319
     Joseph         265306
F    Elizabeth      226808
M    Richard        225494
F    Betty          206953
M    George         200709
F    Linda          200041
     Barbara        181592
M    Joshua         180616
F    Patricia       178825
M    Matthew        176009
F    Sarah          173186
M    Kenneth        168455
F    Margaret       168333
     Dorothy        166371
M    Daniel         165611
Name: Count, dtype: int64

## Part 5 — Visualization (Pandas +

1.   List item
2.   List item

Plotly)

In [ ]:
import plotly.express as px

bar_df = by_cat.head(10).reset_index()
fig = px.bar(bar_df, x=category_col, y=numeric_col, title=f'Top 10 {category_col} (interactive)')
fig.show()

## Part 6 — Reflection
- What needed adjusting when you switched datasets?
- What was easier/harder vs the workbook?
- What context/limitations should a policymaker know?

## Part 7 — ⚡ Lightning Chart Demos — Teach-Out Instructions

### What is a Lightning Demo?
A **rapid-fire mini-presentation**: 2 minutes per group. Show **one chart** + **one insight**, not your whole notebook.

### Demo Format (2 minutes)
1. **Context (15 sec):** Dataset name + 1-sentence purpose.  
2. **Chart + Insight (75–90 sec):** Show interactive Plotly chart; state one clear finding; name one wrangling step.  
3. **Caveat or Next Step (15–30 sec):** One limitation OR next idea.  
4. **Pass the mic (10 sec):** End with *“Any questions about our chart?”*

### Unique Angles
- Aggregation choice (sum vs mean, raw vs normalized).  
- Data cleaning step (conversion, deduping).  
- Encoding (bar vs line vs scatter).  
- Interactivity (facet, hover, filter).  
- Comparability (per capita vs raw counts).  
- Temporal nuance (trend vs snapshot).  

👉 If another group showed your angle, pick a different one.

### Flow for the Day
- Groups present **clustered by chart type** (bars, lines, scatter, other).  
- Instructor summarizes similarities/differences after each cluster.  
- 15 groups × 2 min = ~30 minutes + transitions = ~40 minutes.

### Presenter Checklist
- [ ] Dataset URL loads in Colab  
- [ ] Columns chosen make sense  
- [ ] One **interactive Plotly figure** with title + labels  
- [ ] Insight stated in one sentence  
- [ ] One cleaning step mentioned  

### Audience Task
After each cluster, jot 1 sentence:  
- What was **similar** across charts?  
- What was **different** (aggregation, encoding, interactivity)?  
- Which chart best supported a **policy decision**—and why?

---
### Quick Rubric (3 pts)
- **Clarity of claim (1 pt)**  
- **Method fit (1 pt)**  
- **Insight/caveat (1 pt)**  
(Bonus +0.5 for meaningful interactivity)

---
### Minimal Code Patterns

**Top-N bar:**
```python
bar_df = df.groupby(category_col)[numeric_col].sum().nlargest(10).reset_index()
fig = px.bar(bar_df, x=category_col, y=numeric_col,
             title=f"Top 10 {category_col} by {numeric_col}")
fig.show()
```

**Time series:**
```python
ts = (df.groupby(time_col)[numeric_col]
        .sum()
        .reset_index()
        .sort_values(time_col))
fig = px.line(ts, x=time_col, y=numeric_col, markers=True,
              title=f"{numeric_col} over time")
fig.show()
```

**Scatter:**
```python
fig = px.scatter(df, x=x_col, y=y_col, trendline="ols",
                 title=f"{y_col} vs {x_col}")
fig.show()
```

---